//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public long id { get; set; }
        public string City { get; set; }
        public string Kommune { get; set; }
        public Nullable<int> Postnummer { get; set; }
        public string Vejnavn { get; set; }
        public Nullable<int> Vejnummer { get; set; }
    
        public virtual BidInfo BidInfo { get; set; }
    }
}
