//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentation
    {
        public long id { get; set; }
        public Nullable<System.DateTime> DatoForRegistrering { get; set; }
        public string DokumentationsInfo { get; set; }
        public string RegistreringsNummer { get; set; }
        public Nullable<System.DateTime> Tilladelse_Gyldig { get; set; }
        public Nullable<int> Tilladelse_Nummer { get; set; }
        public string Tilladelse_Type { get; set; }
        public string TrafikSelskab { get; set; }
        public string UdstedendeMyndighed { get; set; }
        public Nullable<long> KlarTilDrift_id { get; set; }
    
        public virtual BidInfo BidInfo { get; set; }
    }
}
