//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class Equipment
    {
        [DataMember]
        public long id { get; set; }
        [DataMember]
        public Nullable<bool> Barnestol_0_13kg { get; set; }
        [DataMember]
        public Nullable<bool> Barnestol_15_36kg { get; set; }
        [DataMember]
        public Nullable<bool> Barnestol_9_18kg { get; set; }
        [DataMember]
        public Nullable<bool> Barnestol_9_36kg { get; set; }
        [DataMember]
        public Nullable<bool> Barnestol_Integreret { get; set; }
        [DataMember]
        public Nullable<bool> TrappeMaskine_120 { get; set; }
        [DataMember]
        public Nullable<bool> TrappeMaskine_160 { get; set; }
        [DataMember]
        public virtual BidInfo BidInfo { get; set; }
    }
}
