//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public long id { get; set; }
        public bool Barnestol_0_13kg { get; set; }
        public bool Barnestol_15_36kg { get; set; }
        public bool Barnestol_9_18kg { get; set; }
        public bool Barnestol_9_36kg { get; set; }
        public bool Barnestol_Integreret { get; set; }
        public bool TrappeMaskine_120 { get; set; }
        public bool TrappeMaskine_160 { get; set; }
    
        public virtual BidInfo BidInfo { get; set; }
    }
}
