//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fynbusprojektEntities : DbContext
    {
        public fynbusprojektEntities()
            : base("name=fynbusprojektEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BidInfo> BidInfo { get; set; }
        public DbSet<ContactInfo> ContactInfo { get; set; }
        public DbSet<Documentation> Documentation { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<ExpandedBidInfo> ExpandedBidInfo { get; set; }
        public DbSet<PriceList> PriceList { get; set; }
    }
}
