//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceList
    {
        public long id { get; set; }
        public int HverdagAftenNatKoersel { get; set; }
        public int HverdagAftenNatOpstartsGebyr { get; set; }
        public int HverdagAftenNatVentetid { get; set; }
        public int HverdageKoersel { get; set; }
        public int HverdageOpstartsGebyr { get; set; }
        public int HverdageVenteTid { get; set; }
        public int PrisPerLoeft_Trappemaskine { get; set; }
        public int WeekendHelligdagKoersel { get; set; }
        public int WeekendHelligdagOpstartsGebyr { get; set; }
        public int WeekendHelligdagVentetid { get; set; }
        public string YderligInfo { get; set; }
    
        public virtual BidInfo BidInfo { get; set; }
    }
}
