//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpandedBidInfo
    {
        public long id { get; set; }
        public int GarantiVognNummer { get; set; }
        public int RegSerieNummer { get; set; }
        public string SecondaryOS { get; set; }
        public int TelefonNummer { get; set; }
        public int VognType { get; set; }
        public int VognloebsNummer { get; set; }
    
        public virtual BidInfo BidInfo { get; set; }
    }
}
