//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.APIService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BidInfo", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class BidInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BidderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CVRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.APIService.ContactInfo ContactInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.APIService.Documentation DocumentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.APIService.Equipment EquipmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.APIService.ExpandedBidInfo ExpandedBidInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastEditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OfferNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.APIService.PriceList PriceListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BidderName {
            get {
                return this.BidderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BidderNameField, value) != true)) {
                    this.BidderNameField = value;
                    this.RaisePropertyChanged("BidderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CVR {
            get {
                return this.CVRField;
            }
            set {
                if ((this.CVRField.Equals(value) != true)) {
                    this.CVRField = value;
                    this.RaisePropertyChanged("CVR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.APIService.ContactInfo ContactInfo {
            get {
                return this.ContactInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactInfoField, value) != true)) {
                    this.ContactInfoField = value;
                    this.RaisePropertyChanged("ContactInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.APIService.Documentation Documentation {
            get {
                return this.DocumentationField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentationField, value) != true)) {
                    this.DocumentationField = value;
                    this.RaisePropertyChanged("Documentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.APIService.Equipment Equipment {
            get {
                return this.EquipmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentField, value) != true)) {
                    this.EquipmentField = value;
                    this.RaisePropertyChanged("Equipment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.APIService.ExpandedBidInfo ExpandedBidInfo {
            get {
                return this.ExpandedBidInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpandedBidInfoField, value) != true)) {
                    this.ExpandedBidInfoField = value;
                    this.RaisePropertyChanged("ExpandedBidInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastEdit {
            get {
                return this.LastEditField;
            }
            set {
                if ((this.LastEditField.Equals(value) != true)) {
                    this.LastEditField = value;
                    this.RaisePropertyChanged("LastEdit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfferNumber {
            get {
                return this.OfferNumberField;
            }
            set {
                if ((this.OfferNumberField.Equals(value) != true)) {
                    this.OfferNumberField = value;
                    this.RaisePropertyChanged("OfferNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.APIService.PriceList PriceList {
            get {
                return this.PriceListField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceListField, value) != true)) {
                    this.PriceListField = value;
                    this.RaisePropertyChanged("PriceList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactInfo", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class ContactInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.APIService.BidInfo BidInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KommuneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VejnavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VejnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.APIService.BidInfo BidInfo {
            get {
                return this.BidInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.BidInfoField, value) != true)) {
                    this.BidInfoField = value;
                    this.RaisePropertyChanged("BidInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kommune {
            get {
                return this.KommuneField;
            }
            set {
                if ((object.ReferenceEquals(this.KommuneField, value) != true)) {
                    this.KommuneField = value;
                    this.RaisePropertyChanged("Kommune");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Postnummer {
            get {
                return this.PostnummerField;
            }
            set {
                if ((this.PostnummerField.Equals(value) != true)) {
                    this.PostnummerField = value;
                    this.RaisePropertyChanged("Postnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vejnavn {
            get {
                return this.VejnavnField;
            }
            set {
                if ((object.ReferenceEquals(this.VejnavnField, value) != true)) {
                    this.VejnavnField = value;
                    this.RaisePropertyChanged("Vejnavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vejnummer {
            get {
                return this.VejnummerField;
            }
            set {
                if ((this.VejnummerField.Equals(value) != true)) {
                    this.VejnummerField = value;
                    this.RaisePropertyChanged("Vejnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documentation", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Documentation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.APIService.BidInfo BidInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatoForRegistreringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DokumentationsInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> KlarTilDrift_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistreringsNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Tilladelse_GyldigField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Tilladelse_NummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tilladelse_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrafikSelskabField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UdstedendeMyndighedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.APIService.BidInfo BidInfo {
            get {
                return this.BidInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.BidInfoField, value) != true)) {
                    this.BidInfoField = value;
                    this.RaisePropertyChanged("BidInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DatoForRegistrering {
            get {
                return this.DatoForRegistreringField;
            }
            set {
                if ((this.DatoForRegistreringField.Equals(value) != true)) {
                    this.DatoForRegistreringField = value;
                    this.RaisePropertyChanged("DatoForRegistrering");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DokumentationsInfo {
            get {
                return this.DokumentationsInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DokumentationsInfoField, value) != true)) {
                    this.DokumentationsInfoField = value;
                    this.RaisePropertyChanged("DokumentationsInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KlarTilDrift_id {
            get {
                return this.KlarTilDrift_idField;
            }
            set {
                if ((this.KlarTilDrift_idField.Equals(value) != true)) {
                    this.KlarTilDrift_idField = value;
                    this.RaisePropertyChanged("KlarTilDrift_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistreringsNummer {
            get {
                return this.RegistreringsNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistreringsNummerField, value) != true)) {
                    this.RegistreringsNummerField = value;
                    this.RaisePropertyChanged("RegistreringsNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Tilladelse_Gyldig {
            get {
                return this.Tilladelse_GyldigField;
            }
            set {
                if ((this.Tilladelse_GyldigField.Equals(value) != true)) {
                    this.Tilladelse_GyldigField = value;
                    this.RaisePropertyChanged("Tilladelse_Gyldig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Tilladelse_Nummer {
            get {
                return this.Tilladelse_NummerField;
            }
            set {
                if ((this.Tilladelse_NummerField.Equals(value) != true)) {
                    this.Tilladelse_NummerField = value;
                    this.RaisePropertyChanged("Tilladelse_Nummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tilladelse_Type {
            get {
                return this.Tilladelse_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Tilladelse_TypeField, value) != true)) {
                    this.Tilladelse_TypeField = value;
                    this.RaisePropertyChanged("Tilladelse_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrafikSelskab {
            get {
                return this.TrafikSelskabField;
            }
            set {
                if ((object.ReferenceEquals(this.TrafikSelskabField, value) != true)) {
                    this.TrafikSelskabField = value;
                    this.RaisePropertyChanged("TrafikSelskab");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UdstedendeMyndighed {
            get {
                return this.UdstedendeMyndighedField;
            }
            set {
                if ((object.ReferenceEquals(this.UdstedendeMyndighedField, value) != true)) {
                    this.UdstedendeMyndighedField = value;
                    this.RaisePropertyChanged("UdstedendeMyndighed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Equipment", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Equipment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Barnestol_0_13kgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Barnestol_15_36kgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Barnestol_9_18kgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Barnestol_9_36kgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Barnestol_IntegreretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.APIService.BidInfo BidInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TrappeMaskine_120Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TrappeMaskine_160Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Barnestol_0_13kg {
            get {
                return this.Barnestol_0_13kgField;
            }
            set {
                if ((this.Barnestol_0_13kgField.Equals(value) != true)) {
                    this.Barnestol_0_13kgField = value;
                    this.RaisePropertyChanged("Barnestol_0_13kg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Barnestol_15_36kg {
            get {
                return this.Barnestol_15_36kgField;
            }
            set {
                if ((this.Barnestol_15_36kgField.Equals(value) != true)) {
                    this.Barnestol_15_36kgField = value;
                    this.RaisePropertyChanged("Barnestol_15_36kg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Barnestol_9_18kg {
            get {
                return this.Barnestol_9_18kgField;
            }
            set {
                if ((this.Barnestol_9_18kgField.Equals(value) != true)) {
                    this.Barnestol_9_18kgField = value;
                    this.RaisePropertyChanged("Barnestol_9_18kg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Barnestol_9_36kg {
            get {
                return this.Barnestol_9_36kgField;
            }
            set {
                if ((this.Barnestol_9_36kgField.Equals(value) != true)) {
                    this.Barnestol_9_36kgField = value;
                    this.RaisePropertyChanged("Barnestol_9_36kg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Barnestol_Integreret {
            get {
                return this.Barnestol_IntegreretField;
            }
            set {
                if ((this.Barnestol_IntegreretField.Equals(value) != true)) {
                    this.Barnestol_IntegreretField = value;
                    this.RaisePropertyChanged("Barnestol_Integreret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.APIService.BidInfo BidInfo {
            get {
                return this.BidInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.BidInfoField, value) != true)) {
                    this.BidInfoField = value;
                    this.RaisePropertyChanged("BidInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TrappeMaskine_120 {
            get {
                return this.TrappeMaskine_120Field;
            }
            set {
                if ((this.TrappeMaskine_120Field.Equals(value) != true)) {
                    this.TrappeMaskine_120Field = value;
                    this.RaisePropertyChanged("TrappeMaskine_120");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TrappeMaskine_160 {
            get {
                return this.TrappeMaskine_160Field;
            }
            set {
                if ((this.TrappeMaskine_160Field.Equals(value) != true)) {
                    this.TrappeMaskine_160Field = value;
                    this.RaisePropertyChanged("TrappeMaskine_160");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpandedBidInfo", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class ExpandedBidInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.APIService.BidInfo BidInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GarantiVognNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegSerieNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondaryOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VognTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VognloebsNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.APIService.BidInfo BidInfo {
            get {
                return this.BidInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.BidInfoField, value) != true)) {
                    this.BidInfoField = value;
                    this.RaisePropertyChanged("BidInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GarantiVognNummer {
            get {
                return this.GarantiVognNummerField;
            }
            set {
                if ((this.GarantiVognNummerField.Equals(value) != true)) {
                    this.GarantiVognNummerField = value;
                    this.RaisePropertyChanged("GarantiVognNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegSerieNummer {
            get {
                return this.RegSerieNummerField;
            }
            set {
                if ((this.RegSerieNummerField.Equals(value) != true)) {
                    this.RegSerieNummerField = value;
                    this.RaisePropertyChanged("RegSerieNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondaryOS {
            get {
                return this.SecondaryOSField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondaryOSField, value) != true)) {
                    this.SecondaryOSField = value;
                    this.RaisePropertyChanged("SecondaryOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TelefonNummer {
            get {
                return this.TelefonNummerField;
            }
            set {
                if ((this.TelefonNummerField.Equals(value) != true)) {
                    this.TelefonNummerField = value;
                    this.RaisePropertyChanged("TelefonNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VognType {
            get {
                return this.VognTypeField;
            }
            set {
                if ((this.VognTypeField.Equals(value) != true)) {
                    this.VognTypeField = value;
                    this.RaisePropertyChanged("VognType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VognloebsNummer {
            get {
                return this.VognloebsNummerField;
            }
            set {
                if ((this.VognloebsNummerField.Equals(value) != true)) {
                    this.VognloebsNummerField = value;
                    this.RaisePropertyChanged("VognloebsNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceList", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class PriceList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.APIService.BidInfo BidInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HverdagAftenNatKoerselField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HverdagAftenNatOpstartsGebyrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HverdagAftenNatVentetidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HverdageKoerselField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HverdageOpstartsGebyrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HverdageVenteTidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrisPerLoeft_TrappemaskineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeekendHelligdagKoerselField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeekendHelligdagOpstartsGebyrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeekendHelligdagVentetidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YderligInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.APIService.BidInfo BidInfo {
            get {
                return this.BidInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.BidInfoField, value) != true)) {
                    this.BidInfoField = value;
                    this.RaisePropertyChanged("BidInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HverdagAftenNatKoersel {
            get {
                return this.HverdagAftenNatKoerselField;
            }
            set {
                if ((this.HverdagAftenNatKoerselField.Equals(value) != true)) {
                    this.HverdagAftenNatKoerselField = value;
                    this.RaisePropertyChanged("HverdagAftenNatKoersel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HverdagAftenNatOpstartsGebyr {
            get {
                return this.HverdagAftenNatOpstartsGebyrField;
            }
            set {
                if ((this.HverdagAftenNatOpstartsGebyrField.Equals(value) != true)) {
                    this.HverdagAftenNatOpstartsGebyrField = value;
                    this.RaisePropertyChanged("HverdagAftenNatOpstartsGebyr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HverdagAftenNatVentetid {
            get {
                return this.HverdagAftenNatVentetidField;
            }
            set {
                if ((this.HverdagAftenNatVentetidField.Equals(value) != true)) {
                    this.HverdagAftenNatVentetidField = value;
                    this.RaisePropertyChanged("HverdagAftenNatVentetid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HverdageKoersel {
            get {
                return this.HverdageKoerselField;
            }
            set {
                if ((this.HverdageKoerselField.Equals(value) != true)) {
                    this.HverdageKoerselField = value;
                    this.RaisePropertyChanged("HverdageKoersel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HverdageOpstartsGebyr {
            get {
                return this.HverdageOpstartsGebyrField;
            }
            set {
                if ((this.HverdageOpstartsGebyrField.Equals(value) != true)) {
                    this.HverdageOpstartsGebyrField = value;
                    this.RaisePropertyChanged("HverdageOpstartsGebyr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HverdageVenteTid {
            get {
                return this.HverdageVenteTidField;
            }
            set {
                if ((this.HverdageVenteTidField.Equals(value) != true)) {
                    this.HverdageVenteTidField = value;
                    this.RaisePropertyChanged("HverdageVenteTid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrisPerLoeft_Trappemaskine {
            get {
                return this.PrisPerLoeft_TrappemaskineField;
            }
            set {
                if ((this.PrisPerLoeft_TrappemaskineField.Equals(value) != true)) {
                    this.PrisPerLoeft_TrappemaskineField = value;
                    this.RaisePropertyChanged("PrisPerLoeft_Trappemaskine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WeekendHelligdagKoersel {
            get {
                return this.WeekendHelligdagKoerselField;
            }
            set {
                if ((this.WeekendHelligdagKoerselField.Equals(value) != true)) {
                    this.WeekendHelligdagKoerselField = value;
                    this.RaisePropertyChanged("WeekendHelligdagKoersel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WeekendHelligdagOpstartsGebyr {
            get {
                return this.WeekendHelligdagOpstartsGebyrField;
            }
            set {
                if ((this.WeekendHelligdagOpstartsGebyrField.Equals(value) != true)) {
                    this.WeekendHelligdagOpstartsGebyrField = value;
                    this.RaisePropertyChanged("WeekendHelligdagOpstartsGebyr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WeekendHelligdagVentetid {
            get {
                return this.WeekendHelligdagVentetidField;
            }
            set {
                if ((this.WeekendHelligdagVentetidField.Equals(value) != true)) {
                    this.WeekendHelligdagVentetidField = value;
                    this.RaisePropertyChanged("WeekendHelligdagVentetid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YderligInfo {
            get {
                return this.YderligInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.YderligInfoField, value) != true)) {
                    this.YderligInfoField = value;
                    this.RaisePropertyChanged("YderligInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetName", ReplyAction="http://tempuri.org/IService1/GetNameResponse")]
        string GetName(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetName", ReplyAction="http://tempuri.org/IService1/GetNameResponse")]
        System.Threading.Tasks.Task<string> GetNameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBidinfo", ReplyAction="http://tempuri.org/IService1/GetBidinfoResponse")]
        Web.APIService.BidInfo GetBidinfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBidinfo", ReplyAction="http://tempuri.org/IService1/GetBidinfoResponse")]
        System.Threading.Tasks.Task<Web.APIService.BidInfo> GetBidinfoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetContactInfo", ReplyAction="http://tempuri.org/IService1/GetContactInfoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.BidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ContactInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Documentation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Equipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ExpandedBidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.PriceList))]
        object GetContactInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetContactInfo", ReplyAction="http://tempuri.org/IService1/GetContactInfoResponse")]
        System.Threading.Tasks.Task<object> GetContactInfoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDocumentation", ReplyAction="http://tempuri.org/IService1/GetDocumentationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.BidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ContactInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Documentation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Equipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ExpandedBidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.PriceList))]
        object GetDocumentation(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDocumentation", ReplyAction="http://tempuri.org/IService1/GetDocumentationResponse")]
        System.Threading.Tasks.Task<object> GetDocumentationAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEquipment", ReplyAction="http://tempuri.org/IService1/GetEquipmentResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.BidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ContactInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Documentation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Equipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ExpandedBidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.PriceList))]
        object GetEquipment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEquipment", ReplyAction="http://tempuri.org/IService1/GetEquipmentResponse")]
        System.Threading.Tasks.Task<object> GetEquipmentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExpandedBifInfo", ReplyAction="http://tempuri.org/IService1/GetExpandedBifInfoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.BidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ContactInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Documentation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Equipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ExpandedBidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.PriceList))]
        object GetExpandedBifInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExpandedBifInfo", ReplyAction="http://tempuri.org/IService1/GetExpandedBifInfoResponse")]
        System.Threading.Tasks.Task<object> GetExpandedBifInfoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPriceList", ReplyAction="http://tempuri.org/IService1/GetPriceListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.BidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ContactInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Documentation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Equipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ExpandedBidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.PriceList))]
        object GetPriceList(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPriceList", ReplyAction="http://tempuri.org/IService1/GetPriceListResponse")]
        System.Threading.Tasks.Task<object> GetPriceListAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateBidInfo", ReplyAction="http://tempuri.org/IService1/CreateBidInfoResponse")]
        Web.APIService.BidInfo CreateBidInfo(string newBid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateBidInfo", ReplyAction="http://tempuri.org/IService1/CreateBidInfoResponse")]
        System.Threading.Tasks.Task<Web.APIService.BidInfo> CreateBidInfoAsync(string newBid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateContactInfo", ReplyAction="http://tempuri.org/IService1/CreateContactInfoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.BidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ContactInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Documentation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Equipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ExpandedBidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.PriceList))]
        object CreateContactInfo(Web.APIService.BidInfo newBid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateContactInfo", ReplyAction="http://tempuri.org/IService1/CreateContactInfoResponse")]
        System.Threading.Tasks.Task<object> CreateContactInfoAsync(Web.APIService.BidInfo newBid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateDocumentation", ReplyAction="http://tempuri.org/IService1/CreateDocumentationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.BidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ContactInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Documentation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Equipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ExpandedBidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.PriceList))]
        object CreateDocumentation(Web.APIService.BidInfo newBid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateDocumentation", ReplyAction="http://tempuri.org/IService1/CreateDocumentationResponse")]
        System.Threading.Tasks.Task<object> CreateDocumentationAsync(Web.APIService.BidInfo newBid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateEquipment", ReplyAction="http://tempuri.org/IService1/CreateEquipmentResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.BidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ContactInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Documentation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Equipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ExpandedBidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.PriceList))]
        object CreateEquipment(Web.APIService.BidInfo newBid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateEquipment", ReplyAction="http://tempuri.org/IService1/CreateEquipmentResponse")]
        System.Threading.Tasks.Task<object> CreateEquipmentAsync(Web.APIService.BidInfo newBid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateExpandedBifInfo", ReplyAction="http://tempuri.org/IService1/CreateExpandedBifInfoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.BidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ContactInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Documentation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Equipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ExpandedBidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.PriceList))]
        object CreateExpandedBifInfo(Web.APIService.BidInfo newBid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateExpandedBifInfo", ReplyAction="http://tempuri.org/IService1/CreateExpandedBifInfoResponse")]
        System.Threading.Tasks.Task<object> CreateExpandedBifInfoAsync(Web.APIService.BidInfo newBid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatePriceList", ReplyAction="http://tempuri.org/IService1/CreatePriceListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.BidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ContactInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Documentation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Equipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ExpandedBidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.PriceList))]
        object CreatePriceList(Web.APIService.BidInfo newBid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatePriceList", ReplyAction="http://tempuri.org/IService1/CreatePriceListResponse")]
        System.Threading.Tasks.Task<object> CreatePriceListAsync(Web.APIService.BidInfo newBid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBidInfo", ReplyAction="http://tempuri.org/IService1/UpdateBidInfoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.BidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ContactInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Documentation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.Equipment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.ExpandedBidInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Web.APIService.PriceList))]
        object UpdateBidInfo(object newBid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBidInfo", ReplyAction="http://tempuri.org/IService1/UpdateBidInfoResponse")]
        System.Threading.Tasks.Task<object> UpdateBidInfoAsync(object newBid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Web.APIService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Web.APIService.IService1>, Web.APIService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetName(int id) {
            return base.Channel.GetName(id);
        }
        
        public System.Threading.Tasks.Task<string> GetNameAsync(int id) {
            return base.Channel.GetNameAsync(id);
        }
        
        public Web.APIService.BidInfo GetBidinfo(int id) {
            return base.Channel.GetBidinfo(id);
        }
        
        public System.Threading.Tasks.Task<Web.APIService.BidInfo> GetBidinfoAsync(int id) {
            return base.Channel.GetBidinfoAsync(id);
        }
        
        public object GetContactInfo(int id) {
            return base.Channel.GetContactInfo(id);
        }
        
        public System.Threading.Tasks.Task<object> GetContactInfoAsync(int id) {
            return base.Channel.GetContactInfoAsync(id);
        }
        
        public object GetDocumentation(int id) {
            return base.Channel.GetDocumentation(id);
        }
        
        public System.Threading.Tasks.Task<object> GetDocumentationAsync(int id) {
            return base.Channel.GetDocumentationAsync(id);
        }
        
        public object GetEquipment(int id) {
            return base.Channel.GetEquipment(id);
        }
        
        public System.Threading.Tasks.Task<object> GetEquipmentAsync(int id) {
            return base.Channel.GetEquipmentAsync(id);
        }
        
        public object GetExpandedBifInfo(int id) {
            return base.Channel.GetExpandedBifInfo(id);
        }
        
        public System.Threading.Tasks.Task<object> GetExpandedBifInfoAsync(int id) {
            return base.Channel.GetExpandedBifInfoAsync(id);
        }
        
        public object GetPriceList(int id) {
            return base.Channel.GetPriceList(id);
        }
        
        public System.Threading.Tasks.Task<object> GetPriceListAsync(int id) {
            return base.Channel.GetPriceListAsync(id);
        }
        
        public Web.APIService.BidInfo CreateBidInfo(string newBid) {
            return base.Channel.CreateBidInfo(newBid);
        }
        
        public System.Threading.Tasks.Task<Web.APIService.BidInfo> CreateBidInfoAsync(string newBid) {
            return base.Channel.CreateBidInfoAsync(newBid);
        }
        
        public object CreateContactInfo(Web.APIService.BidInfo newBid) {
            return base.Channel.CreateContactInfo(newBid);
        }
        
        public System.Threading.Tasks.Task<object> CreateContactInfoAsync(Web.APIService.BidInfo newBid) {
            return base.Channel.CreateContactInfoAsync(newBid);
        }
        
        public object CreateDocumentation(Web.APIService.BidInfo newBid) {
            return base.Channel.CreateDocumentation(newBid);
        }
        
        public System.Threading.Tasks.Task<object> CreateDocumentationAsync(Web.APIService.BidInfo newBid) {
            return base.Channel.CreateDocumentationAsync(newBid);
        }
        
        public object CreateEquipment(Web.APIService.BidInfo newBid) {
            return base.Channel.CreateEquipment(newBid);
        }
        
        public System.Threading.Tasks.Task<object> CreateEquipmentAsync(Web.APIService.BidInfo newBid) {
            return base.Channel.CreateEquipmentAsync(newBid);
        }
        
        public object CreateExpandedBifInfo(Web.APIService.BidInfo newBid) {
            return base.Channel.CreateExpandedBifInfo(newBid);
        }
        
        public System.Threading.Tasks.Task<object> CreateExpandedBifInfoAsync(Web.APIService.BidInfo newBid) {
            return base.Channel.CreateExpandedBifInfoAsync(newBid);
        }
        
        public object CreatePriceList(Web.APIService.BidInfo newBid) {
            return base.Channel.CreatePriceList(newBid);
        }
        
        public System.Threading.Tasks.Task<object> CreatePriceListAsync(Web.APIService.BidInfo newBid) {
            return base.Channel.CreatePriceListAsync(newBid);
        }
        
        public object UpdateBidInfo(object newBid) {
            return base.Channel.UpdateBidInfo(newBid);
        }
        
        public System.Threading.Tasks.Task<object> UpdateBidInfoAsync(object newBid) {
            return base.Channel.UpdateBidInfoAsync(newBid);
        }
    }
}
